version: '3.8'

services:
  mongo:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  api:
    build:
      context: .
      args:
        SERVICE_NAME: api
    ports:
      - "8001:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
      - WEBHOOK_SECRET=supersecret
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  worker:
    build:
      context: .
      args:
        SERVICE_NAME: worker
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

volumes:
  mongo_data:
